## Que 1

#### (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 

In [1]:
import numpy as np

In [8]:
arr = np.array([1,2,3,6,4,5])
arr

array([1, 2, 3, 6, 4, 5])

In [9]:
reverse_arr = arr[::-1]
reverse_arr

array([5, 4, 6, 3, 2, 1])

#### (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods 

In [10]:
arr = np.array([[1,2,3],[2,4,5],[1,2,3]])
arr.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

#### (c) Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[1, 2], [3, 4]])


In [11]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

In [12]:
arr1 == arr2

array([[ True,  True],
       [ True,  True]])

#### (d) Find the most frequent value and their indice(s) in the following arrays: (i). x = np.array([1,2,3,4,5,1,2,1,1,1]) (ii). y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 


In [13]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

In [25]:
max_x = np.bincount(x).argmax()
print("Most frequent value: ", max_x)
print("Indices of most frequent value: ", np.where(x == max_x)[0])

Most frequent value:  1
Indices of most frequent value:  [0 5 7 8 9]


In [17]:
y = np.array([1,1,1,2,3,4,2,4,3,3])

In [24]:
new_y = np.bincount(y)
max_y = max(new_y)

for i in range(len(new_y)):
    if new_y[i] == max_y:
        print("Most frequent value: ", i)
        print("Indices of most frequent value: ", (np.where(y == i)[0]))

Most frequent value:  1
Indices of most frequent value:  [0 1 2]
Most frequent value:  3
Indices of most frequent value:  [4 8 9]


#### (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find (i). Sum of all elements (ii). Sum of all elements row-wise (iii). Sum of all elements column-wise

In [26]:
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')

In [34]:
# Total sum
gfg.sum()

np.int64(45)

In [32]:
# Row-wise sum
gfg.sum(axis=1)

matrix([[14],
        [16],
        [15]])

In [33]:
# Column-wise sum
gfg.sum(axis=0)

matrix([[20,  9, 16]])

#### (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find (i). Sum of diagonal elements (ii). Eigen values of matrix (iii). Eigen vectors of matrix (iv). Inverse of matrix (v). Determinant of matrix 

In [35]:
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])

In [37]:
# Sum of diagonal elements
n_array.trace()

np.int64(176)

In [42]:
# Eigen Value and Eigen Vector of matrix
eig_val, eig_vec = np.linalg.eig(n_array)
print("Eigen Value: ", eig_val)
print("Eigen Vector: ", eig_vec)

Eigen Value:  [98.16835147 28.097044   49.73460452]
Eigen Vector:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [41]:
# Inverse of matrix
np.linalg.inv(n_array)

array([[ 0.02404141, -0.00911212, -0.00444671],
       [-0.01667882,  0.02966905,  0.0024785 ],
       [ 0.00631287, -0.01603732,  0.01217379]])

In [43]:
# Determinant of matrix
np.linalg.det(n_array)

np.float64(137180.0000000001)

#### (g) Multiply the following matrices and also find covariance between matrices using NumPy: i. p = [[1, 2], [2, 3]] q = [[4, 5], [6, 7]] (ii). p = [[1, 2], [2, 3], [4, 5]] q = [[4, 5, 1], [6, 7, 2]]

In [45]:
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
np.multiply(p,q)

array([[ 4, 10],
       [12, 21]])

In [46]:
p = np.array([[1,2],[2,3],[4,5]])
q = np.array([[4,5,1],[6,7,2]])
np.multiply(p,q)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

#### (h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), find inner, outer and cartesian product?


In [50]:
x = np.array([[2,3,4], [3,2,9]])
y = np.array([[1,5,0],[5, 10, 3]])

print("Inner Product: ", np.inner(x,y))
print("Outer Product: ", np.outer(x,y))

a,b = np.meshgrid(x,y)
cart_prod = np.stack((a.flatten(), b.flatten()), axis=1)
print("Cartesian Product: ", cart_prod)

Inner Product:  [[17 52]
 [13 62]]
Outer Product:  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product:  [[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


### Que 2

#### (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) (i). Find element-wise absolute value (ii). Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row. (iii). Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [53]:
array = np.array([[1,-2,3], [-4,5,-6]])

In [55]:
# Absolute value
np.abs(array)

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
row_25 = np.percentile(array, 25, axis=1)
col_25 = np.percentile(array, 25, axis=0)
row_50 = np.percentile(array, 50, axis=1)
col_50 = np.percentile(array, 50, axis=0)
row_75 = np.percentile(array, 75, axis=1)
col_75 = np.percentile(array, 75, axis=0)

print("25th percentile for row: ", row_25)
print("25th percentile for column:", col_25)
print("50th percentile for row:", row_50)
print("50th percentile for column:", col_50)
print("75th percentile for row:", row_75)
print("75th percentile for column:", col_75)

25th percentile for row:  [-0.5 -5. ]
25th percentile for column: [-2.75 -0.25 -3.75]
50th percentile for row: [ 1. -4.]
50th percentile for column: [-1.5  1.5 -1.5]
75th percentile for row: [2.  0.5]
75th percentile for column: [-0.25  3.25  0.75]


In [61]:
row_mean = np.mean(array, axis=1)
col_mean = np.mean(array, axis=0)
row_median = np.median(array, axis=1)
col_median = np.median(array, axis=0)
row_std = np.std(array, axis=1)
col_std = np.std(array, axis=0)

print(f"Row Mean: {row_mean}")
print(f"Column Mean: {col_mean}")
print(f"Row Median: {row_median}")
print(f"Column Median: {col_median}")
print(f"Row Standard Deviation: {row_std}")
print(f"Column Standard Deviation: {col_std}")

Row Mean: [ 0.66666667 -1.66666667]
Column Mean: [-1.5  1.5 -1.5]
Row Median: [ 1. -4.]
Column Median: [-1.5  1.5 -1.5]
Row Standard Deviation: [2.05480467 4.78423336]
Column Standard Deviation: [2.5 3.5 4.5]


#### (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values

In [62]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

In [63]:
print(f"Floor: {np.floor(a)}")
print(f"Ceiling: {np.ceil(a)}")
print(f"Truncate: {np.trunc(a)}")
print(f"Rounded: {np.round(a)}")

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncate: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


### Que 3

#### (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find (i). Sorted array (ii). Indices of sorted array (iii). 4th smallest elements (iv). 5th largest elements

In [4]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

In [19]:
# Sorted array
sorted_arr = np.sort(array)
sorted_arr

array([ 10,  16,  16,  52,  54,  62, 453])

In [20]:
# Indices of sorted array
np.argsort(sorted_arr)

array([0, 1, 2, 3, 4, 5, 6])

In [21]:
# 4th smallest element
sorted_arr[3]

np.int64(52)

In [24]:
# 5th largest element
sorted_arr[-5]

np.int64(16)

#### (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find (i). Integer elements only (ii). Float elements only

In [34]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [42]:
for i in array:
    if type(array[0])==int:
        print(i)

In [81]:
# Integer elements
if array.dtype==int:
    print(array)

In [82]:
# Float elements
if array.dtype==float:
    print(array)

[1.  1.2 2.2 2.  3.  2. ]


### Que 4

#### (a) Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)
#### (b) Load the saved file into jupyter notebook? 

In [ ]:
from Pillow import Image
import numpy as np

def img_to_array(path):
    
    img = Image.open(path)
    
    if img.mode == 'L':  # Grayscale
        img_array = np.array(img)
        file_name = 'grayscale_image_array.txt'
    elif img.mode == 'RGB':  # RGB
        img_array = np.array(img)
        file_name = 'rgb_image_array.txt'
    else:
        raise ValueError("Unsupported image mode: only 'L' (grayscale) and 'RGB' are supported")
    
    if img.mode == 'L':
        np.savetxt(file_name, img_array, fmt='%d')
    else:
        np.savetxt(file_name, img_array.reshape(-1, img_array.shape[2]), fmt='%d,%d,%d')
    
    print(f"Image array saved as {file_name}")

img_to_array(r'C:\Users\hp\OneDrive\Documents\Pictures\hacker1.jpg')